In [197]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display 
from sklearn.ensemble import RandomForestClassifier 
%matplotlib inline

In [198]:
def display_all(df):
    with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000): 
        display(df)

In [199]:
df1=pd.read_csv('train.csv',low_memory=True)

In [200]:
df2=pd.read_csv('test.csv',low_memory=True)

In [201]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [202]:
df2.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [203]:
df1.shape

(891, 12)

In [204]:
df2.shape

(418, 11)

In [205]:
df=pd.concat([df1,df2])
df.shape

(1309, 12)

In [206]:
display_all(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [207]:
clf=RandomForestClassifier(n_jobs=-1)

In [209]:
df['Title']=list(map(lambda x: x.split('.')[0].split(',')[1],df.Name))

In [210]:
df.Title

0           Mr
1          Mrs
2         Miss
3          Mrs
4           Mr
        ...
413         Mr
414       Dona
415         Mr
416         Mr
417     Master
Name: Title, Length: 1309, dtype: object

In [211]:
d=df[df['Title'].str.contains("Mme")]
display_all(d)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
369,370,1.0,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3,B35,C,Mme

In [57]:
18738.5/757

24.753632760898284

In [54]:
d['Age'].sum()/len(d['Age'])

26.23427672955975

In [212]:
#for Miss 17.6
#For Ms 28
#For Dr 38.125
#For Master 4.8
#For Mr 24.8
#For Mrs 32

len(Mrs)=197, len(Mr)=954-197
sum(Mrs)=6289, sum(Mr)=25027.5-6289
avg=32,      avg=24.8

In [213]:
df['Title'] = df['Title'].replace({'Miss' : 17.6}, regex=True)
df['Title'] = df['Title'].replace({'Ms' : 28}, regex=True)
df['Title'] = df['Title'].replace({'Dr' : 38.1}, regex=True)
df['Title'] = df['Title'].replace({'Master' : 4.8}, regex=True)
df['Title'] = df['Title'].replace({'Mr' : 24.8}, regex=True)
df['Title'] = df['Title'].replace({'Mrs' : 32}, regex=True)

In [114]:
pd.get_dummies(df.Title)

,4.8,17.6,24.8,28,38.1,Capt,Col,Don,Dona,Jonkheer,Lady,Major,Mlle,Mme,Rev,Sir,the Countess
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
414,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
415,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
416,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
417,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [214]:
df['Age']=df['Age'].fillna(value=(df['Title']))

In [222]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0.0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,2,24.8
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,0,24.8
2,3,1.0,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,2,17.6
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,2,24.8
4,5,0.0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,2,24.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",1,24.8,0,0,A.5. 3236,8.0500,NaN,2,24.8
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",0,39.0,0,0,PC 17758,108.9000,C105,0,Dona
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",1,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,2,24.8
416,1308,NaN,3,"Ware, Mr. Frederick",1,24.8,0,0,359309,8.0500,NaN,2,24.8
417,1309,NaN,3,"Peter, Master. Michael J",1,4.8,1,1,2668,22.3583,NaN,0,4.8

In [252]:
df['Sex'] = df['Sex'].astype('category').cat.codes

In [253]:
df['Embarked'] = df['Embarked'].astype('category').cat.codes

In [254]:
y=df.Survived

In [255]:
y.dropna(inplace=True)

In [256]:
y.shape

(891,)

In [257]:
y=y.astype('int64')

In [258]:
train = df.iloc[:891, :]
test= df.iloc[891:,:]

In [259]:
test.isna().sum()

PassengerId      0
Survived       418
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
Title            0
dtype: int64

In [240]:
d=df.where(df['Pclass']>2)

In [241]:
d['Fare'].sum()/709

13.284125811001408

In [242]:
len(d)-600

709

In [243]:
d.isna().sum()

PassengerId     600
Survived        818
Pclass          600
Name            600
Sex             600
Age             600
SibSp           600
Parch           600
Ticket          600
Fare            601
Cabin          1293
Embarked        600
Title           600
dtype: int64

In [251]:
df['Fare']=df['Fare'].fillna(value=13.28)

In [260]:
x_train=train[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [261]:
x_test=test[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [262]:
clf.fit(x_train,y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [248]:
display_all(x_test)

     PassengerId  Pclass  Sex    Age  SibSp  Parch      Fare  Embarked
0            892       3    1  34.50      0      0    7.8292         2
1            893       3    0  47.00      1      0    7.0000         3
2            894       2    1  62.00      0      0    9.6875         2
3            895       3    1  27.00      0      0    8.6625         3
4            896       3    0  22.00      1      1   12.2875         3
5            897       3    1  14.00      0      0    9.2250         3
6            898       3    0  30.00      0      0    7.6292         2
7            899       2    1  26.00      1      1   29.0000         3
8            900       3    0  18.00      0      0    7.2292         1
9            901       3    1  21.00      2      0   24.1500         3
10           902       3    1  24.80      0      0    7.8958         3
11           903       1    1  46.00      0      0   26.0000         3
12           904       1    0  23.00      1      0   82.2667         3
13           905       2    1  63.00      1      0   26.0000         3
14           906       1    0  47.00      1      0   61.1750         3
15           907       2    0  24.00      1      0   27.7208         1
16           908       2    1  35.00      0      0   12.3500         2
17           909       3    1  21.00      0      0    7.2250         1
18           910       3    0  27.00      1      0    7.9250         3
19           911       3    0  45.00      0      0    7.2250         1
20           912       1    1  55.00      1      0   59.4000         1
21           913       3    1   9.00      0      1    3.1708         3
22           914       1    0  24.80      0      0   31.6833         3
23           915       1    1  21.00      0      1   61.3792         1
24           916       1    0  48.00      1      3  262.3750         1
25           917       3    1  50.00      1      0   14.5000         3
26           918       1    0  22.00      0      1   61.9792         1
27           919       3    1  22.50      0      0    7.2250         1
28           920       1    1  41.00      0      0   30.5000         3
29           921       3    1  24.80      2      0   21.6792         1
30           922       2    1  50.00      1      0   26.0000         3
31           923       2    1  24.00      2      0   31.5000         3
32           924       3    0  33.00      1      2   20.5750         3
33           925       3    0  24.80      1      2   23.4500         3
34           926       1    1  30.00      1      0   57.7500         1
35           927       3    1  18.50      0      0    7.2292         1
36           928       3    0  17.60      0      0    8.0500         3
37           929       3    0  21.00      0      0    8.6625         3
38           930       3    1  25.00      0      0    9.5000         3
39           931       3    1  24.80      0      0   56.4958         3
40           932       3    1  39.00      0      1   13.4167         1
41           933       1    1  24.80      0      0   26.5500         3
42           934       3    1  41.00      0      0    7.8500         3
43           935       2    0  30.00      0      0   13.0000         3
44           936       1    0  45.00      1      0   52.5542         3
45           937       3    1  25.00      0      0    7.9250         3
46           938       1    1  45.00      0      0   29.7000         1
47           939       3    1  24.80      0      0    7.7500         2
48           940       1    0  60.00      0      0   76.2917         1
49           941       3    0  36.00      0      2   15.9000         3
50           942       1    1  24.00      1      0   60.0000         3
51           943       2    1  27.00      0      0   15.0333         1
52           944       2    0  20.00      2      1   23.0000         3
53           945       1    0  28.00      3      2  263.0000         3
54           946       2    1  24.80      0      0   15.5792         1
55           947       3    1  10.00      4      1   29.1250         2
56           948       3    1  35.00      0      0    7.8958         3
57           949       3    1  25.00      0      0    7.6500         3
58           950       3    1  24.80      1      0   16.1000         3
59           951       1    0  36.00      0      0  262.3750         1
60           952       3    1  17.00      0      0    7.8958         3
61           953       2    1  32.00      0      0   13.5000         3
62           954       3    1  18.00      0      0    7.7500         3
63           955       3    0  22.00      0      0    7.7250         2
64           956       1    1  13.00      2      2  262.3750         1
65           957       2    0  24.80      0      0   21.0000         3
66           958       3    0  18.00      0      0    7.8792         2
67           959       1    1  47.00      0      0   42.4000         3
68           960       1    1  31.00      0      0   28.5375         1
69           961       1    0  60.00      1      4  263.0000         3
70           962       3    0  24.00      0      0    7.7500         2
71           963       3    1  21.00      0      0    7.8958         3
72           964       3    0  29.00      0      0    7.9250         3
73           965       1    1  28.50      0      0   27.7208         1
74           966       1    0  35.00      0      0  211.5000         1
75           967       1    1  32.50      0      0  211.5000         1
76           968       3    1  24.80      0      0    8.0500         3
77           969       1    0  55.00      2      0   25.7000         3
78           970       2    1  30.00      0      0   13.0000         3
79           971       3    0  24.00      0      0    7.7500         2
80           972       3    1   6.00      1      1   15.2458         1
81           973       1    1  67.00      1      0  221.7792         3
82           974       1    1  49.00      0      0   26.0000         3
83           975       3    1  24.80      0      0    7.8958         3
84           976       2    1  24.80      0      0   10.7083         2
85           977       3    1  24.80      1      0   14.4542         1
86           978       3    0  27.00      0      0    7.8792         2
87           979       3    0  18.00      0      0    8.0500         3
88           980       3    0  28.00      0      0    7.7500         2
89           981       2    1   2.00      1      1   23.0000         3
90           982       3    0  22.00      1      0   13.9000         3
91           983       3    1  24.80      0      0    7.7750         3
92           984       1    0  27.00      1      2   52.0000         3
93           985       3    1  24.80      0      0    8.0500         3
94           986       1    1  25.00      0      0   26.0000         1
95           987       3    1  25.00      0      0    7.7958         3
96           988       1    0  76.00      1      0   78.8500         3
97           989       3    1  29.00      0      0    7.9250         3
98           990       3    0  20.00      0      0    7.8542         3
99           991       3    1  33.00      0      0    8.0500         3
100          992       1    0  43.00      1      0   55.4417         1
101          993       2    1  27.00      1      0   26.0000         3
102          994       3    1  24.80      0      0    7.7500         2
103          995       3    1  26.00      0      0    7.7750         3
104          996       3    0  16.00      1      1    8.5167         1
105          997       3    1  28.00      0      0   22.5250         3
106          998       3    1  21.00      0      0    7.8208         2
107          999       3    1  24.80      0      0    7.7500         2
108         1000       3    1  24.80      0      0    8.7125         3
109         1001       2    1  18.50      0      0   13.0000         3
110         1002       2    1  41.00      0      0   15.0458         1
111         1003       3    0  17.60      0      0    7.7792         2
112         1004       1    0  36.00      0      0   31.6792         1
113         1005       3    0  18.50      0      0    7.2833         2
114         1006       1    0  63.00      1      0  221.7792         3
115         1007       3    1  18.00      1      0   14.4542         1
116         1008       3    1  24.80      0      0    6.4375         1
117         1009       3    0   1.00      1      1   16.7000         3
118         1010       1    1  36.00      0      0   75.2417         1
119         1011       2    0  29.00      1      0   26.0000         3
120         1012       2    0  12.00      0      0   15.7500         3
121         1013       3    1  24.80      1      0    7.7500         2
122         1014       1    0  35.00      1      0   57.7500         1
123         1015       3    1  28.00      0      0    7.2500         3
124         1016       3    1  24.80      0      0    7.7500         2
125         1017       3    0  17.00      0      1   16.1000         3
126         1018       3    1  22.00      0      0    7.7958         3
127         1019       3    0  17.60      2      0   23.2500         2
128         1020       2    1  42.00      0      0   13.0000         3
129         1021       3    1  24.00      0      0    8.0500         3
130         1022       3    1  32.00      0      0    8.0500         3
131         1023       1    1  53.00      0      0   28.5000         1
132         1024       3    0  24.80      0      4   25.4667         3
133         1025       3    1  24.80      1      0    6.4375         1
134         1026       3    1  43.00      0      0    7.8958         3
135         1027       3    1  24.00      0      0    7.8542         3
136         1028       3    1  26.50      0      0    7.2250         1
137         1029       2    1  26.00      0      0   13.0000         3
138         1030       3    0  23.00      0      0    8.0500         3
139         1031       3    1  40.00      1      6   46.9000         3
140         1032       3    0  10.00      5      2   46.9000         3
141         1033       1    0  33.00      0      0  151.5500         3
142         1034       1    1  61.00      1      3  262.3750         1
143         1035       2    1  28.00      0      0   26.0000         3
144         1036       1    1  42.00      0      0   26.5500         3
145         1037       3    1  31.00      3      0   18.0000         3
146         1038       1    1  24.80      0      0   51.8625         3
147         1039       3    1  22.00      0      0    8.0500         3
148         1040       1    1  24.80      0      0   26.5500         3
149         1041       2    1  30.00      1      1   26.0000         3
150         1042       1    0  23.00      0      1   83.1583         1
151         1043       3    1  24.80      0      0    7.8958         1
152         1044       3    1  60.50      0      0       NaN         3
153         1045       3    0  36.00      0      2   12.1833         3
154         1046       3    1  13.00      4      2   31.3875         3
155         1047       3    1  24.00      0      0    7.5500         3
156         1048       1    0  29.00      0      0  221.7792         3
157         1049       3    0  23.00      0      0    7.8542         3
158         1050       1    1  42.00      0      0   26.5500         3
159         1051       3    0  26.00      0      2   13.7750         3
160         1052       3    0  17.60      0      0    7.7333         2
161         1053       3    1   7.00      1      1   15.2458         1
162         1054       2    0  26.00      0      0   13.5000         3
163         1055       3    1  24.80      0      0    7.0000         3
164         1056       2    1  41.00      0      0   13.0000         3
165         1057       3    0  26.00      1      1   22.0250         3
166         1058       1    1  48.00      0      0   50.4958         1
167         1059       3    1  18.00      2      2   34.3750         3
168         1060       1    0  24.80      0      0   27.7208         1
169         1061       3    0  22.00      0      0    8.9625         3
170         1062       3    1  24.80      0      0    7.5500         3
171         1063       3    1  27.00      0      0    7.2250         1
172         1064       3    1  23.00      1      0   13.9000         3
173         1065       3    1  24.80      0      0    7.2292         1
174         1066       3    1  40.00      1      5   31.3875         3
175         1067       2    0  15.00      0      2   39.0000         3
176         1068       2    0  20.00      0      0   36.7500         3
177         1069       1    1  54.00      1      0   55.4417         1
178         1070       2    0  36.00      0      3   39.0000         3
179         1071       1    0  64.00      0      2   83.1583         1
180         1072       2    1  30.00      0      0   13.0000         3
181         1073       1    1  37.00      1      1   83.1583         1
182         1074       1    0  18.00      1      0   53.1000         3
183         1075       3    1  24.80      0      0    7.7500         2
184         1076       1    0  27.00      1      1  247.5208         1
185         1077       2    1  40.00      0      0   16.0000         3
186         1078       2    0  21.00      0      1   21.0000         3
187         1079       3    1  17.00      2      0    8.0500         3
188         1080       3    0  17.60      8      2   69.5500         3
189         1081       2    1  40.00      0      0   13.0000         3
190         1082       2    1  34.00      1      0   26.0000         3
191         1083       1    1  24.80      0      0   26.0000         3
192         1084       3    1  11.50      1      1   14.5000         3
193         1085       2    1  61.00      0      0   12.3500         2
194         1086       2    1   8.00      0      2   32.5000         3
195         1087       3    1  33.00      0      0    7.8542         3
196         1088       1    1   6.00      0      2  134.5000         1
197         1089       3    0  18.00      0      0    7.7750         3
198         1090       2    1  23.00      0      0   10.5000         3
199         1091       3    0  24.80      0      0    8.1125         3
200         1092       3    0  17.60      0      0   15.5000         2
201         1093       3    1   0.33      0      2   14.4000         3
202         1094       1    1  47.00      1      0  227.5250         1
203         1095       2    0   8.00      1      1   26.0000         3
204         1096       2    1  25.00      0      0   10.5000         3
205         1097       1    1  24.80      0      0   25.7417         1
206         1098       3    0  35.00      0      0    7.7500         2
207         1099       2    1  24.00      0      0   10.5000         3
208         1100       1    0  33.00      0      0   27.7208         1
209         1101       3    1  25.00      0      0    7.8958         3
210         1102       3    1  32.00      0      0   22.5250         3
211         1103       3    1  24.80      0      0    7.0500         3
212         1104       2    1  17.00      0      0   73.5000         3
213         1105       2    0  60.00      1      0   26.0000         3
214         1106       3    0  38.00      4      2    7.7750         3
215         1107       1    1  42.00      0      0   42.5000         3
216         1108       3    0  17.60      0      0    7.8792         2
217         1109       1    1  57.00      1      1  164.8667         3
218         1110       1    0  50.00      1      1  211.5000         1
219         1111       3    1  24.80      0      0    8.0500         3
220         1112       2    0  30.00      1      0   13.8583         1
221         1113       3    1  21.00      0      0    8.0500         3
222         1114       2    0  22.00      0      0   10.5000         3
223         1115       3    1  21.00      0      0    7.7958         3
224         1116       1    0  53.00      0      0   27.4458         1
225         1117       3    0  24.80      0      2   15.2458         1
226         1118       3    1  23.00      0      0    7.7958         3
227         1119       3    0  17.60      0      0    7.7500         2
228         1120       3    1  40.50      0      0   15.1000         3
229         1121       2    1  36.00      0      0   13.0000         3
230         1122       2    1  14.00      0      0   65.0000         3
231         1123       1    0  21.00      0      0   26.5500         3
232         1124       3    1  21.00      1      0    6.4958         3
233         1125       3    1  24.80      0      0    7.8792         2
234         1126       1    1  39.00      1      0   71.2833         1
235         1127       3    1  20.00      0      0    7.8542         3
236         1128       1    1  64.00      1      0   75.2500         1
237         1129       3    1  20.00      0      0    7.2250         1
238         1130       2    0  18.00      1      1   13.0000         3
239         1131       1    0  48.00      1      0  106.4250         1
240         1132       1    0  55.00      0      0   27.7208         1
241         1133       2    0  45.00      0      2   30.0000         3
242         1134       1    1  45.00      1      1  134.5000         1
243         1135       3    1  24.80      0      0    7.8875         3
244         1136       3    1   4.80      1      2   23.4500         3
245         1137       1    1  41.00      1      0   51.8625         3
246         1138       2    0  22.00      0      0   21.0000         3
247         1139       2    1  42.00      1      1   32.5000         3
248         1140       2    0  29.00      1      0   26.0000         3
249         1141       3    0  24.80      1      0   14.4542         1
250         1142       2    0   0.92      1      2   27.7500         3
251         1143       3    1  20.00      0      0    7.9250         3
252         1144       1    1  27.00      1      0  136.7792         1
253         1145       3    1  24.00      0      0    9.3250         3
254         1146       3    1  32.50      0      0    9.5000         3
255         1147       3    1  24.80      0      0    7.5500         3
256         1148       3    1  24.80      0      0    7.7500         2
257         1149       3    1  28.00      0      0    8.0500         3
258         1150       2    0  19.00      0      0   13.0000         3
259         1151       3    1  21.00      0      0    7.7750         3
260         1152       3    1  36.50      1      0   17.4000         3
261         1153       3    1  21.00      0      0    7.8542         3
262         1154       2    0  29.00      0      2   23.0000         3
263         1155       3    0   1.00      1      1   12.1833         3
264         1156       2    1  30.00      0      0   12.7375         1
265         1157       3    1  24.80      0      0    7.8958         3
266         1158       1    1  24.80      0      0    0.0000         3
267         1159       3    1  24.80      0      0    7.5500         3
268         1160       3    0  17.60      0      0    8.0500         3
269         1161       3    1  17.00      0      0    8.6625         3
270         1162       1    1  46.00      0      0   75.2417         1
271         1163       3    1  24.80      0      0    7.7500         2
272         1164       1    0  26.00      1      0  136.7792         1
273         1165       3    0  17.60      1      0   15.5000         2
274         1166       3    1  24.80      0      0    7.2250         1
275         1167       2    0  20.00      1      0   26.0000         3
276         1168       2    1  28.00      0      0   10.5000         3
277         1169       2    1  40.00      1      0   26.0000         3
278         1170       2    1  30.00      1      0   21.0000         3
279         1171       2    1  22.00      0      0   10.5000         3

In [238]:
x_test.isna().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [263]:
pred=clf.predict(x_test)

In [264]:
output=pd.DataFrame(data={"PassengerId":x_test["PassengerId"],"Survived":pred})

In [265]:
output

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [ ]:
output.to_csv(r'C:\Users\Madhavan Suriya\Downloads\Projects\titanic\output.csv',index=False)

In [ ]:
output.shape